### PR TITLE
add user wesleybryie

### PR DESCRIPTION
**Pull request by polymo1**
proof of identity:

https://wesbryie.com

https://github.com/sidestore/anisette-servers

can email wes@wesbryie.com

### CODE REVIEW

**Comment by adsr** [comment]
Hi @polymo1. Can you pick a username <= 10 chars? Thanks.

**Comment by polymo1** [comment]
Sure, don't have access to my computer right now. I'll do it when I can, or `polymo1` works

**Comment by polymo1** [comment]
@adsr alright change done, lmk if theres any issues

**Comment by adsr** [comment]
Thanks

**Pull request merged**
